---
title: "SE10"
author: "William Han"
date: "3/8/2022"
output: html_document
---

```{r}
library(janitor)
library(lubridate)
library(tidyverse)
library(ggpubr)
library(rvest)
```

```{r}
group_A <- readr::read_csv(here::here("SE10/data/Attitudes on AI  - Group A-control.csv"))
group_B <- readr::read_csv(here::here("SE10/data/Attitudes on AI  - Group B-experiment.csv"))
```

```{r}
glimpse(group_A)
glimpse(group_B)
```

```{r}
group_A |> 
  ggplot(aes(x = work_and_school)) + 
  geom_bar()
```


```{r}
group_A |> 
  group_by(work_and_school) |> 
  count()
```
```{r}
group_B |> 
  group_by(work_and_school) |> 
  count()
```


group A

science 

6/15 - computer
4/15 - social
2/15 - physical
3/15 - psychological

group B

science 

11/21 - computer
3/21 - social
0/21 - physical
7/21 - psychological


```{r}
group_A |> 
  group_by(household_income_yearly) |> 
  count()
```

```{r}
group_B |> 
  group_by(yearly_household_income) |> 
  count()
```

8 - less than 5,000
6 - 5,000 - 9,000
4 - 10,000 - 14,999
4 - 15,000 - 19,999
4 - 20,000 - 29,999
15 - 30,000 - 39,999
4 - 40,000 - 49,999
8 - 50,000 - 59,999
9 - 60,000 - 74,999
8 - 75,000 - 99,999
8 - 100,000 - 124,999
22 - 125,000 - 149,999


```{r}
group_A |> 
  group_by(Age) |> 
  count()
```

```{r}
group_B |> 
  group_by(age) |> 
  count()
```

under 22 - 63
between 22 and 30 - 21
30 and above - 16